"""rename column name in contacts table.

Revision ID: 0204fa9c5022
Revises: ec7298b150ef
Create Date: 2025-04-28 11:35:45.787032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0204fa9c5022'
down_revision = 'ec7298b150ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
