"""create templates table.

Revision ID: 257a97c3abd1
Revises: 546d26d5823b
Create Date: 2025-04-25 12:41:53.778344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257a97c3abd1'
down_revision = '546d26d5823b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
