"""create user table

Revision ID: 505f557129b7
Revises: 
Create Date: 2025-04-23 11:05:20.542935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505f557129b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
