"""add school_name column in user table.

Revision ID: 6cf0cf44c77d
Revises: fa46f5f66495
Create Date: 2025-04-29 12:29:36.567625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf0cf44c77d'
down_revision = 'fa46f5f66495'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
