"""add school_name column in user table.

Revision ID: 841c582d9479
Revises: c35dba516847
Create Date: 2025-04-29 12:30:22.870548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841c582d9479'
down_revision = 'c35dba516847'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
