"""create tables.

Revision ID: 9fabde48a4e3
Revises: 841c582d9479
Create Date: 2025-04-29 12:31:38.753310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fabde48a4e3'
down_revision = '841c582d9479'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
