"""create school table and add realtionship between school and user table

Revision ID: a345791ff8ee
Revises: 728bd4239b60
Create Date: 2025-04-30 12:44:47.371584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a345791ff8ee'
down_revision = '728bd4239b60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
