"""add school_name column in user table.

Revision ID: c35dba516847
Revises: 6cf0cf44c77d
Create Date: 2025-04-29 12:29:51.616000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35dba516847'
down_revision = '6cf0cf44c77d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
