"""add subject column in template table.

Revision ID: e5ca6b282b64
Revises: 9fabde48a4e3
Create Date: 2025-04-29 12:40:52.785028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ca6b282b64'
down_revision = '9fabde48a4e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_templates_id', table_name='templates')
    op.drop_table('templates')
    op.drop_index('ix_contacts_id', table_name='contacts')
    op.drop_index('ix_contacts_student_name', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_refresh_token_id', table_name='refresh_token')
    op.drop_index('ix_refresh_token_user_email', table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index('ix_message_logs_id', table_name='message_logs')
    op.drop_table('message_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('message_type', sa.VARCHAR(), nullable=False),
    sa.Column('recipient', sa.VARCHAR(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_logs_id', 'message_logs', ['id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_email', sa.VARCHAR(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('blacklisted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_token_user_email', 'refresh_token', ['user_email'], unique=False)
    op.create_index('ix_refresh_token_id', 'refresh_token', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('mobile_no', sa.VARCHAR(), nullable=True),
    sa.Column('school_name', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('otp', sa.VARCHAR(), nullable=True),
    sa.Column('otp_created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('student_name', sa.VARCHAR(), nullable=False),
    sa.Column('parent_name', sa.VARCHAR(), nullable=False),
    sa.Column('parent_email', sa.VARCHAR(), nullable=True),
    sa.Column('parent_phone_no', sa.VARCHAR(), nullable=True),
    sa.Column('mode', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_student_name', 'contacts', ['student_name'], unique=False)
    op.create_index('ix_contacts_id', 'contacts', ['id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_templates_id', 'templates', ['id'], unique=False)
    # ### end Alembic commands ###
