"""rename column name in contacts table.

Revision ID: f86994803362
Revises: 2600dcf9a777
Create Date: 2025-04-28 12:00:07.905981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86994803362'
down_revision = '2600dcf9a777'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
